server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 499cb2237807a3882c8b3dc4c1679ad10905afdca646822c252f489769057ef6
# ${{ secrets.DATASOURCE_PASS }}
    url: jdbc:postgresql://ec2-34-242-89-204.eu-west-1.compute.amazonaws.com:5432/d908fvnh6u2q86
    username: txuuhhvtmebbtb
#    ${{ secrets.DATASOURCE_USER }}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: runningeventsmail@gmail.com
    password:  ${{ secrets.EMAIL_PASS }}

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
